# Codecov Configuration

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 10%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.mocks.dart"
  - "**/generated/**"
  - "test/**"
  - "integration_test/**"
  - "lib/firebase_options.dart"
